version: '3.8'

services:
  db_postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=siikli
      - POSTGRES_USER=siikli
      - POSTGRES_PASSWORD=testpassword
    ports:
      - '5432:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - siikli

  redis:
    image: redis:latest
    command: ['redis-server', '/etc/redis/redis.conf']
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf

volumes:
  db_postgres:
  redis_data:

networks:
  siikli:
    driver: bridge
