-- AlterTable
ALTER TABLE "product" ALTER COLUMN "name" SET DATA TYPE VARCHAR(64),
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "type" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "variety" DROP NOT NULL,
ALTER COLUMN "variety" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "info" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "price0" DROP NOT NULL;
